<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.8" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Novolis.Game.Identity.Abstractions" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Game.Identity.AspNetCore" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Messaging.SecureText" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Security.SecureText" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Testing.TestBases" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Testing.TUnit" Version="2026.1.*" />
    <PackageVersion Include="TUnit" Version="1.68.17" />
  </ItemGroup>
</Project>
